### ISSUE TITLE
vue-router 4.1.5 使用报错

### ISSUE THREAD

**Issue by nannan527** [Zippowxk/stack-keep-alive#10]
RT

**Comment by Zippowxk** [comment]
已在sample code中测试，4.1.5， 并未报错。请提供更多报错信息，或者参考代码 https://github.com/Zippowxk/stack-keep-alive-sample/tree/vue-router-4.1.5

**Comment by Zippowxk** [comment]
暂时排除vue-router 4.1.5 导致报错的可能性

**Comment by nannan527** [comment]
@Zippowxk 
> 暂时排除vue-router 4.1.5 导致报错的可能性

好像是 vue-cli webpack 编辑的问题，
我用 vue-router 4.0.16 其它不动都没问题，升级成 4.1.5 `，webpack编译就报错，换成vite就没问题。

[localhost-1663135790312.log](https://github.com/Zippowxk/stack-keep-alive/files/9563246/localhost-1663135790312.log)

**Comment by Zippowxk** [comment]
> 



> @Zippowxk
> 
> > 暂时排除vue-router 4.1.5 导致报错的可能性
> 
> 好像是 vue-cli webpack 编辑的问题， 我用 vue-router 4.0.16 其它不动都没问题，升级成 4.1.5 `，webpack编译就报错，换成vite就没问题。
> 
> [localhost-1663135790312.log](https://github.com/Zippowxk/stack-keep-alive/files/9563246/localhost-1663135790312.log)

示例代码中就是用的 vue-cli ，没见到有什么问题。日志中没有什么有价值的信息供分析。

**Comment by nannan527** [comment]
嗯，好的谢谢。我研究下了是 vue-router@4.1.1 这里为了 vitest 删除了 "browser":"./dist/vue-router.esm-browser.js"。
![QQ20220914-162611](https://user-images.githubusercontent.com/4023533/190102654-236a416d-9fff-4eed-baf2-2dd77d3c9443.png)
我把它加回去就可以运行了,留一笔 给需要ts项目转译 ‘esnext’ 需要 esm-browser 的留个参考
