### ISSUE TITLE
当存在嵌套路由的时候，返回上一个页面报错

### ISSUE THREAD

**Issue by MatthewTt** [Zippowxk/stack-keep-alive#12]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/23712720/210521772-35df0771-c663-480b-bcb7-4b73abd9960f.png">

**Comment by Zippowxk** [comment]
目前不支持嵌套路由

**Comment by saikete** [comment]
老哥有没有计划支持一下

**Comment by Zippowxk** [comment]
嵌套路由在手机端几乎没有应用场景吧

**Comment by saikete** [comment]
（是想用在pc端

**Comment by Zippowxk** [comment]
非常遗憾，嵌套路由不适合这套自动管理的逻辑。并不是技术原因不去支持，纯粹是因为PC端的页面缓存逻辑，没有一套可行的自动化逻辑与之匹配。 更适合使用 exclude 和 include 去动态管理

**Comment by saikete** [comment]
收到的，辛苦，其实也是想找一个能缓存页面栈管理路由插件，总之我会继续寻找合适的，谢谢🙏

**Comment by Zippowxk** [comment]
如果找到了 欢迎追加到评论区，供大家和我学习参考，谢谢

**Comment by saikete** [comment]
有一个大哥写了一个，我还在问追加到我项目里的事，可以看下
https://github.com/Murphy-Tong/page-stack-vue3
