### ISSUE TITLE
是否支持保存页面的滚动条位置

### ISSUE THREAD

**Issue by ChenDoXiu** [Zippowxk/stack-keep-alive#13]
如题，是否支持保存页面的滚动条位置

**Comment by ChenDoXiu** [comment]
当我切换路由的时候，页面的滚动条重置了

**Comment by Zippowxk** [comment]
> 当我切换路由的时候，页面的滚动条重置了
> 
> 

支持，你需要做两件事： 1. 在data中保存位移位置 2. 在activated中使用data中保存的数据重新设置页面位移

**Comment by ChenDoXiu** [comment]
好的，感谢
