### ISSUE TITLE
发现一个新问题，配合vant navbar tab使用的时候会出现navbar无法点击

### ISSUE THREAD

**Issue by zim-lee** [Zippowxk/stack-keep-alive#14]
RT，路由多次切换后会出现导航无法点击，比如左侧按钮

具体操作步骤：

1、首页向下滑动，然后点击进入"关于页面"

2、进入"关于页面"后滚动页面，然后点击顶部左侧按钮返回

多次重复操作后，关于页面的左侧返回按钮会出现无法点击的情况，这种情况目前只有iOS中会出现，安卓正常，大佬帮忙看看啥情况

附件是最小复现demo

[vant-demo1.zip](https://github.com/Zippowxk/stack-keep-alive/files/11303580/vant-demo1.zip)

**Comment by Zippowxk** [comment]
感谢你的反馈 我会尝试复现并尽快给出结论

**Comment by Zippowxk** [comment]
经过简单排查，在不使用stack-keep-alive插件的情况下，依旧可以复现该问题，应该是vant组件库的bug，你可以把问题提交给vant

**Comment by zim-lee** [comment]
不用的情况下我没复现出来，不过用了肯定出现😖

**Comment by Zippowxk** [comment]
我通过修改你的demo已经复现了
