### ISSUE TITLE
vue3使用sk-transition实现动画效果出现丢失滚动位置的现象。

### ISSUE THREAD

**Issue by jaskban** [Zippowxk/stack-keep-alive#18]
您好，我用了sk-transition组件实现动画发现存在一个现象，就是能看到当前页面滚动位置会被自动拉回顶部后再出现切换页面的动画，我需要的动画效果切换到其它页面能保留当前页面的滚动位置，请问这个怎么解决呢？

**Comment by Zippowxk** [comment]
请收 https://github.com/Zippowxk/stack-keep-alive-sample/commits/scroll-position ，框架不需要修改，仅修改动画css代码即可
