### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by zhangguixin** [Zippowxk/stack-keep-alive#3]
No matching export in "node_modules/vue-router/dist/vue-router.esm-bundler.js" for import "default"

    node_modules/stack-keep-alive/dist/library.mjs:3:7:
      3 │ import VueRouter from 'vue-router';
        ╵        ~~~~~~~~~

**Comment by zhangguixin** [comment]
vue@3.2.37 / vue-router

**Comment by zhangguixin** [comment]
"vue": "^3.2.37",
"vue-router": "^4.0.16",
vue-router 的引用方式应该为 import {useRouter} from "vue-router";

**Comment by Zippowxk** [comment]
请使用最新版本stack-keep-alive@1.0.0-beta.4
