### ISSUE TITLE
Vant 切换tab时重复渲染？

### ISSUE THREAD

**Issue by Zippowxk** [Zippowxk/stack-keep-alive#4]
RT

**Comment by SunnyTaday** [comment]
+1

**Comment by Zippowxk** [comment]
经过验证 没有问题，切换tab请使用 replaceStay白名单
```vue
<stack-keep-alive v-slot='{ key }' :replaceStay='["/", "/list"]'>
```

**Comment by Zippowxk** [comment]
> 经过验证 没有问题，切换tab请使用 replaceStay白名单
> 
> ```
> <stack-keep-alive v-slot='{ key }' :replaceStay='["/", "/list"]'>
> ```

参见readme

**Comment by zim-lee** [comment]
有tab配置的完整demo么，我这里配置了白名单依然重复渲染，不知道是哪里不对，能否帮忙看看
[demo.zip](https://github.com/Zippowxk/stack-keep-alive/files/9443690/demo.zip)

**Comment by Zippowxk** [comment]
> 

请看这里 https://github.com/Zippowxk/stack-keep-alive-sample/blob/vant/src/App3.vue

**Comment by zim-lee** [comment]
我提供的demo跟示例不太一样，tab不是入口的第一个页面，是从别的页面跳转到tab页面的，效果就不行了，不管在哪里配置replaceStay都不行

**Comment by Zippowxk** [comment]
> 我提供的demo跟示例不太一样，tab不是入口的第一个页面，是从别的页面跳转到tab页面的，效果就不行了，不管在哪里配置replaceStay都不行

听起来你需要使用singleton模式 这个页面需要全局唯一吗？ goback也不销毁吗

**Comment by zim-lee** [comment]
相当于是登录后的首页，属于路由顶层，肯定也是全局唯一的

**Comment by zim-lee** [comment]
试了singleton模式，结果挺奇怪的，如果入口页面和tab页面都配了，两个tab页会加载两次，后面就不会再加载了，如果只配了入口tab页面就会不断加载，如果只配了tab页，有的页面加载3次，有的两次，后面就不再重复加载了，您可以拿demo试试

**Comment by Zippowxk** [comment]
> 试了singleton模式，结果挺奇怪的，如果入口页面和tab页面都配了，两个tab页会加载两次，后面就不会再加载了，如果只配了入口tab页面就会不断加载，如果只配了tab页，有的页面加载3次，有的两次，后面就不再重复加载了，您可以拿demo试试

我看了你的Demo， stack-keep-alive插件是模拟的Mobile原生内存管理方式，不适合应用在PC端，因为PC端常使用嵌套路由

**Comment by zim-lee** [comment]
嵌套路由这种场景在移动端挺常见的吧，从登录到tab页如果不嵌套，那所有页面不都在tab的框架下了么，并不是所有页面都要显示tab的，总不能不显示的地方都要做个隐藏处理吧

**Comment by Zippowxk** [comment]
> 嵌套路由这种场景在移动端挺常见的吧，从登录到tab页如果不嵌套，那所有页面不都在tab的框架下了么，并不是所有页面都要显示tab的，总不能不显示的地方都要做个隐藏处理吧

反过来考虑，默认隐藏，只在需要的时候展示。仅需少量处理
