### ISSUE TITLE
sk-transition 动画无效

### ISSUE THREAD

**Issue by carrykingdow** [Zippowxk/stack-keep-alive#9]
` <router-view v-slot="{ Component }">
        <sk-transition name="slide-left" back_name="slide-right">
          <stack-keep-alive v-slot="{ key }">
            <component :is="Component" :key="key" />
          </stack-keep-alive>
        </sk-transition>
   </router-view>`

transition 动画没有生效。。。

**Comment by carrykingdow** [comment]
打扰了，居然要手动写入对应的css。。

`
.slide-right-enter-active,
.slide-right-leave-active,
.slide-left-enter-active,
.slide-left-leave-active {
  will-change: transform;
  transition: transform 350ms;
  position: fixed;
  pointer-events: none;
  width: 100%;
  height: 100%;
}
.slide-left-enter-active,
.slide-right-leave-active {
  z-index: 99;
}
.slide-right-enter-from {
  z-index: 1;
  transform: translate3d(-100%, 0, 0);
}
.slide-right-leave-active {
  transition-delay: 100ms;
  transform: translate3d(100%, 0, 0);
}
.slide-left-enter-from {
  transform: translate3d(100%, 0, 0);
}
.slide-left-leave-active {
  transition-delay: 100ms;
  transform: translate3d(-100%, 0, 0);
}`

**Comment by Zippowxk** [comment]
[Demo Here](http://xinkai.wang/stack-keep-alive-sample/dist/)

**Comment by regboy** [comment]
你好，我加上了样式，但是切换的动画还是没有，不知道怎么回事
